routes/web.php
<?php


use Illuminate\Support\Facades\Route;
use Invento\Blog\Controllers\BlogController;
use Invento\Blog\Controllers\CategoryController;
use Invento\Blog\Controllers\ConfigController;

Route::group(['middleware' => ['check.banned.ip','throttle:40,1','web', 'auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::group(['prefix' => 'blogs', 'as' => 'blogs.'], function () {
        Route::resource('categories', CategoryController::class);
    });

    Route::get('packages/config-blog',[ConfigController::class,'index'])->name('packages.config-blog');
    Route::post('packages/blog-store',[ConfigController::class,'store'])->name('packages.blog.store');

    Route::resource('blogs', BlogController::class);

});

resources/views/blogs/create.blade.php
<x-default-layout>

    @push('styles')
        <link rel="stylesheet" href="{{ asset('vendor/file-manager/css/file-manager.css') }}">
        <link rel="stylesheet" href="{{ asset('vendor/file-manager/css/custom.css') }}">
    @endpush

    @section('title')
        {{ __('blog::blogs.add_blog') }}
    @endsection

    @section('breadcrumbs')
        {{ Breadcrumbs::render('blogs.create') }}
    @endsection

    {!! Form::open(array('route' =>'admin.blogs.store', 'method'=>'post','class'=>'form' ,'id' => 'kt_blog_form')) !!}


        <div class="row">
            <div class="col-lg-9">
                <div class="card card-flush py-4">
                    <div class="card-header">
                        <div class="card-title">
                            <h2>{{ __('blog::blogs.blog_details') }}</h2>
                        </div>
                    </div>

                    <div class="card-body pt-0">

                        <div class="mb-10 fv-row">
                            <label class="required form-label">{{ __('blog::blogs.blog_title') }}</label>
                            <input type="text" name="title" id="title" class="form-control mb-2 meta_title" value=""/>
                            <div class="text-muted fs-7">{{ __('blog::blogs.blog_title_text') }}</div>

                        </div>

                        <div class="mb-10 fv-row">
                            <label class="form-label">{{ __('blog::blogs.short_description') }}</label>
                            <textarea rows="5" name="short_description" id="short_description"
                                      class="form-control mb-2 meta_description" placeholder="Product name"> </textarea>
                            <div class="text-muted fs-7">{{ __('blog::blogs.short_description_text') }}</div>

                        </div>

                        <div class="mb-10 fv-row">
                            <label class="form-label">Description</label>
                            <div id="quill-editor" class="min-h-200px mb-2" style="height: 300px;"></div>
                            <textarea rows="3" class="mb-3 d-none" name="content" id="quill-editor-area">

                    </textarea>
                            <div class="text-muted fs-7">{{ __('blog::blogs.content_text') }}</div>
                        </div>

                        <div class="mb-10 fv-row">
                            <label class="form-label">{{ __('blog::blogs.tags') }}</label>

                            <select class="form-select mb-2" name="tag[]" id="tag" data-control="select2" multiple
                                    data-hide-search="false" data-placeholder="Select appropriate tag">
                                <option></option>
                                @foreach($tags as $key => $tag)
                                    <option value="{{ $tag }}">{{ $tag }}</option>
                                @endforeach
                            </select>
                        </div>

                        @include('backend.partials.seo-field',['model' => 'Invento-Blog-Models-Blog','column' => 'slug','seo' => $blog])

                        @custom_fields(\App\Models\CustomField::MODULES['Blog'], null)

                        <div class="mt-10 fv-row">
                            <div class="d-flex justify-content-end">
                                <button type="submit" class="btn btn-primary"><span class="indicator-label">{{ __('blog::blogs.submit') }}</span>
                                </button>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="card card-flush">
                    <div class="card-header">
                        <div class="card-title">
                            <h4>{{ __('blog::blogs.thumbnail') }}</h4>
                        </div>
                    </div>

                    <div class="card-body text-center pt-0">
                        @include('backend.pages.filemanager.input',['image' => '','name' => 'thumbnail'])
                    </div>
                </div>

                <div class="card card-flush">
                    <div class="card-header">
                        <div class="card-title">
                            <h4>{{ __('blog::blogs.is_featured') }}</h4>
                        </div>

                    </div>

                    <div class="card-body pt-0">
                        <label class="form-check form-switch form-check-custom form-check-solid">
                            <input class="form-check-input" name="is_featured" type="checkbox" checked />
                        </label>
                    </div>
                </div>

                <div class="card card-flush">
                    <div class="card-header">
                        <div class="card-title">
                            <h4>{{ __('blog::blogs.category') }}</h4>
                        </div>

                    </div>

                    <div class="card-body pt-0">
                        <select class="form-select mb-2" name="category" id="category" data-control="select2"
                                data-hide-search="false" data-placeholder="Select an category">
                            <option></option>
                            @foreach($categories as $key => $val)
                                <option value="{{ $key }}">{{ $val }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>


                <div class="card card-flush">
                    <div class="card-header">
                        <div class="card-title">
                            <h4>{{ __('blog::blogs.display_order') }}</h4>
                        </div>

                    </div>

                    <div class="card-body pt-0">
                        <input type="number" name="display_order" id="display_order" placeholder="{{ __('blog::blogs.display_order_text') }}" class="form-control" value=""/>
                    </div>
                </div>


                <div class="card card-flush">
                    <div class="card-header">
                        <div class="card-title">
                            <h4>{{ __('blog::blogs.status') }}</h4>
                        </div>
                    </div>

                    <div class="card-body pt-0">
                        <select name="status" id=status class="form-select mb-2" data-control="select2" data-hide-search="true"
                                data-placeholder="{{ __('blog::blogs.status_text') }}">
                            @foreach(\Invento\Blog\Models\Blog::STATUS as $value)
                                <option value="{{ $value }}">{{ $value }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
            </div>
        </div>




    {!! Form::close() !!}


    @push('scripts')
        <script src="{{ asset('vendor/file-manager/js/file-manager.js') }}"></script>
        <script src="{{ asset('vendor/file-manager/js/custom-file-manager.js') }}"></script>

        <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>

        {!! JsValidator::formRequest('Invento\Blog\Requests\BlogRequest', '#kt_blog_form') !!}


        <script>
            document.addEventListener('DOMContentLoaded', function () {
                if (document.getElementById('quill-editor-area')) {
                    var editor = new Quill('#quill-editor', {
                        modules: {
                            toolbar: [
                                ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
                                ['blockquote', 'code-block'],
                                ['link', 'image', 'video', 'formula'],

                                [{'header': 1}, {'header': 2}],               // custom button values
                                [{'list': 'ordered'}, {'list': 'bullet'}, {'list': 'check'}],
                                [{'script': 'sub'}, {'script': 'super'}],      // superscript/subscript
                                [{'indent': '-1'}, {'indent': '+1'}],          // outdent/indent
                                [{'direction': 'rtl'}],                         // text direction

                                [{'size': ['small', false, 'large', 'huge']}],  // custom dropdown
                                [{'header': [1, 2, 3, 4, 5, 6, false]}],

                                [{'color': []}, {'background': []}],          // dropdown with defaults from theme
                                [{'font': []}],
                                [{'align': []}],

                                ['clean']
                            ]
                        },
                        placeholder: 'Type your text here...',
                        theme: 'snow' // or 'bubble'
                    });
                    var quillEditor = document.getElementById('quill-editor-area');
                    editor.on('text-change', function () {
                        quillEditor.value = editor.root.innerHTML;
                    });

                    quillEditor.addEventListener('input', function () {
                        editor.root.innerHTML = quillEditor.value;
                    });
                }
            });
        </script>
    @endpush

</x-default-layout>

resources/views/blogs/index.blade.php
<x-default-layout>

    @section('title')
        {{ __('blog::blogs.blog_list') }}
    @endsection

    @section('breadcrumbs')
        {{ Breadcrumbs::render('blogs.index') }}
    @endsection

    <div class="card card-flush pt-3 mb-5 mb-lg-10">
        <!--begin::Card header-->
        <div class="card-header border-0 pt-5">
            <h3 class="card-title align-items-start flex-column">
                <span class="card-label fw-bold fs-3 mb-1">{{ __('blog::blogs.blog_list') }}</span>
            </h3>
            <div class="card-toolbar">
                <a href="{{ route('admin.blogs.create') }}" class="btn btn-sm btn-primary">
                    <i class="ki-duotone ki-plus fs-2"></i>{{ __('blog::blogs.add_blog') }}</a>
            </div>
        </div>
        <!--end::Card header-->
        <!--begin::Card body-->
        @if(count($blogs))
            <div class="card-body py-4">
                <div class="table-responsive">
                    <!--begin::Table-->
                    <table class="table table-row-dashed table-row-gray-300 align-middle gs-0 gy-4">
                        <!--begin::Table head-->
                        <thead>
                        <tr class="fw-bold text-muted">
                            <th class="w-25px">
                                <div class="form-check form-check-sm form-check-custom form-check-solid">
                                    <input class="form-check-input" type="checkbox" value="1" data-kt-check="true"
                                           data-kt-check-target=".widget-9-check">
                                </div>
                            </th>
                            <th>{{ __('blog::blogs.blog_title') }}</th>
                            <th>{{ __('blog::blogs.category') }}</th>
                            <th class="text-center">{{ __('blog::blogs.publish_status') }}</th>
                            <th class="text-center">{{ __('blog::blogs.is_featured') }}</th>
                            <th class="text-center">{{ __('blog::blogs.display_order') }}</th>
                            <th class="text-center">{{ __('blog::blogs.created_at') }}</th>
                            <th class="pr-0 text-end w-10">{{ __('blog::blogs.action') }}</th>
                        </tr>
                        </thead>
                        <!--end::Table head-->
                        <!--begin::Table body-->
                        <tbody>
                        @foreach($blogs as $blog)

                            <tr>
                                <td>
                                    <div class="form-check form-check-sm form-check-custom form-check-solid">
                                        <input name="id" class="form-check-input widget-9-check" type="checkbox"
                                               value="{{ $blog->id }}">
                                    </div>
                                </td>
                                <td class="w-25">
                                    <div class="d-flex align-items-center">
                                        <div class="symbol symbol-45px me-5">
                                            <img src="{{ $blog->thumbnail }}" alt="{{ __('blog::blogs.thumbnail') }}">
                                        </div>
                                        <div class="d-flex justify-content-start flex-column">
                                            <a href="{{ route('admin.blogs.edit',$blog->id) }}" class="text-dark text-hover-info fs-6">{{ $blog->title }}</a>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <a href="{{ route('admin.blogs.categories.edit',$blog->blog_category_id) }}" class="text-dark text-hover-info d-block fs-6">{{ $blog->category_name }}</a>
                                </td>
                                <td class="text-center d-flex justify-content-center align-items-center border-0">
                                    <label class="form-check form-switch form-check-custom form-check-solid mt-3">
                                        <input class="form-check-input statusCheckbox" name="status" data-id="{{ $blog->id }}" onclick="event.preventDefault(); document.getElementById('statusForm-{{$blog->id}}').submit();"
                                               type="checkbox" {{ $blog->status ? 'checked' : '' }} />
                                    </label>

                                    {!! Form::open(array('route' =>['admin.blogs.update',$blog->id], 'method'=>'patch' ,'id' => 'statusForm-'.$blog->id)) !!}
                                    <input type="hidden" name="status_switch" value="{{ $blog->status }}">
                                    {!! Form::close() !!}
                                </td>

                                <td class="text-center">
                                    <a class="text-dark text-hover-info d-block fs-6">{{ $blog->is_featured ? 'True' : 'False' }}</a>
                                </td>

                                <td class="text-center">
                                    <a class="text-dark text-hover-info d-block fs-6">{{ $blog->display_order }}</a>
                                </td>

                                <td class="text-center">
                                    <a class="text-dark text-hover-info d-block fs-6">{{ date('M d, Y',strtotime($blog->created_at)) }}</a>
                                </td>

                                <td class="text-end">
                                    <a href="#"
                                       class="btn btn-light btn-active-light-primary btn-flex btn-center btn-sm"
                                       data-kt-menu-trigger="click"
                                       data-kt-menu-placement="bottom-end">{{ __('blog::blogs.action') }}
                                        <i class="ki-duotone ki-down fs-5 ms-1"></i></a>

                                    <div
                                            class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-semibold fs-7 w-125px py-4"
                                            data-kt-menu="true">

                                        <div class="menu-item px-3">
                                            <a href="{{ route('admin.blogs.edit',$blog->id) }}"
                                               class="menu-link px-3">{{ __('blog::blogs.edit') }}</a>
                                        </div>

                                        <div class="menu-item px-3">
                                            <a href="#" class="menu-link px-3 delete_table_row"
                                               data-row="{{ $blog->id }}">{{  __('blog::blogs.delete')  }}</a>
                                        </div>

                                        <form id="delete_form_{{ $blog->id }}" method="post"
                                              action="{{ route('admin.blogs.destroy',$blog->id) }}">
                                            @csrf
                                            @method('delete')
                                        </form>

                                    </div>

                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                        <!--end::Table body-->
                    </table>
                    <!--end::Table-->
                </div>

            </div>
        @else
            <div class="card-body p-0">
                <!--begin::Wrapper-->
                <div class="card-px text-center">
                    <!--begin::Title-->
                    <h2 class="fs-2x fw-bold mb-10">{{ __('blog::blogs.welcome_to_blog') }}</h2>
                    <!--end::Title-->

                    <!--begin::Action-->
                    <a href="{{ route('admin.blogs.create') }}"
                       class="btn btn-primary">{{ __('blog::blogs.add_blog') }}</a>
                    <!--end::Action-->
                </div>
                <!--end::Wrapper-->
                <!--begin::Illustration-->
                <div class="text-center px-4">
                    <img class="mw-100 mh-300px" alt="" src="{{ asset('vendor/blog/media/empty_blog.png') }}">
                </div>
                <!--end::Illustration-->
            </div>
        @endif
        <!--end::Card body-->
    </div>


</x-default-layout>

resources/views/categories/create.blade.php
<x-default-layout>

    @section('title')
        {{ __('blog::categories.add_category') }}
    @endsection

    @section('breadcrumbs')
        {{ Breadcrumbs::render('blogs.categories.create') }}
    @endsection

    {!! Form::open(array('route' =>'admin.blogs.categories.store', 'method'=>'post','class'=>'form d-flex flex-column flex-lg-row' ,'id' => 'kt_blog_category_form')) !!}
    <div class="d-flex flex-column flex-row-fluid gap-7 gap-lg-10 me-lg-10">
        <div class="card card-flush py-4">
            <div class="card-header">
                <div class="card-title">
                    <h2>{{ __('blog::categories.category_details') }}</h2>
                </div>
            </div>

            <div class="card-body pt-0">

                <div class="mb-10 fv-row">
                    <label class="required form-label">{{ __('blog::categories.name') }}</label>
                    <input type="text" name="name" id="name" class="form-control mb-2 meta_title meta_url @error('name') is-invalid @enderror" value=""/>

                    @error('name')
                    <div id="name-error" class="invalid-feedback">{{ $message }}</div>
                    @enderror

                    <div class="text-muted fs-7">{{ __('blog::categories.name_text') }}</div>

                </div>

                <div class="mb-10 fv-row">
                    <label class="required form-label">{{ __('blog::categories.display_order') }}</label>
                    <input type="number" name="display_order" id="display_order" class="form-control mb-2 @error('display_order') is-invalid @enderror" value=""/>

                    @error('display_order')
                    <div id="name-error" class="invalid-feedback">{{ $message }}</div>
                    @enderror

                    <div class="text-muted fs-7">{{ __('blog::categories.display_order_text') }}</div>

                </div>

                <div class="mb-10 fv-row">
                    <label class="form-check form-switch form-check-custom form-check-solid">
                        <input class="form-check-input" name="status" type="checkbox" checked/>
                        <span class="form-check-label fw-semibold text-muted">{{ __('blog::categories.status') }}</span>
                    </label>
                </div>


                @include('backend.partials.seo-field',['model' => 'Invento-Blog-Models-Category','column' => 'slug','seo' => $category])

                @custom_fields(\App\Models\CustomField::MODULES['Blog Category'], null)

                <div class="mt-10 fv-row">
                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-primary"><span class="indicator-label">{{__('blog::categories.submit')}}</span>
                        </button>
                    </div>
                </div>

            </div>

        </div>
    </div>
    {!! Form::close() !!}


    @push('scripts')

        <!-- Laravel Javascript Validation -->
        <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>

        {!! JsValidator::formRequest('Invento\Blog\Requests\CategoryRequest', '#kt_blog_category_form') !!}

    @endpush

</x-default-layout>

resources/views/categories/index.blade.php
<x-default-layout>

    @section('title')
        {{ __('blog::categories.category_list') }}
    @endsection

    @section('breadcrumbs')
        {{ Breadcrumbs::render('blogs.categories.index') }}
    @endsection

    <div class="card card-flush pt-3 mb-5 mb-lg-10">
        <!--begin::Card header-->
        <div class="card-header border-0 pt-5">
            <h3 class="card-title align-items-start flex-column">
                <span class="card-label fw-bold fs-3 mb-1">{{ __('blog::categories.category_list') }}</span>
            </h3>
            <div class="card-toolbar">
                <a href="{{ route('admin.blogs.categories.create') }}" class="btn btn-sm btn-primary">
                    <i class="ki-duotone ki-plus fs-2"></i>{{ __('blog::categories.add_category') }}</a>
            </div>
        </div>
        <!--end::Card header-->
        <!--begin::Card body-->
        @if(count($categories))
            <div class="card-body py-4">
                <div class="table-responsive">
                    <!--begin::Table-->
                    <table class="table table-row-dashed table-row-gray-300 align-middle gs-0 gy-4">
                        <!--begin::Table head-->
                        <thead>
                        <tr class="fw-bold text-muted">
                            <th class="w-25px">
                                <div class="form-check form-check-sm form-check-custom form-check-solid">
                                    <input class="form-check-input" type="checkbox" value="1" data-kt-check="true"
                                           data-kt-check-target=".widget-9-check">
                                </div>
                            </th>
                            <th>{{ __('blog::categories.name') }}</th>
                            <th class="text-center">{{ __('blog::categories.display_order') }}</th>
                            <th class="text-center">{{ __('blog::categories.status') }}</th>
                            <th class="text-center">{{ __('blog::categories.created_at') }}</th>
                            <th class="pr-0 text-end w-10">{{ __('blog::categories.action') }}</th>
                        </tr>
                        </thead>
                        <!--end::Table head-->
                        <!--begin::Table body-->
                        <tbody>
                        @foreach($categories as $category)
                            <tr>
                                <td>
                                    <div class="form-check form-check-sm form-check-custom form-check-solid">
                                        <input name="id" class="form-check-input widget-9-check" type="checkbox"
                                               value="{{ $category->id }}">
                                    </div>
                                </td>

                                <td>
                                    <a href="{{ route('admin.blogs.categories.edit',$category->id) }}"
                                       class="text-dark fw-bold text-hover-primary d-block fs-6">{{ $category->name }}</a>
                                </td>

                                <td class="text-center">
                                    {{ $category->display_order ?? 'Null' }}
                                </td>

                                <td class="text-center d-flex justify-content-center align-items-center border-0">
                                    <label class="form-check form-switch form-check-custom form-check-solid mt-3">
                                        <input class="form-check-input statusCheckbox" name="status" data-id="{{ $category->id }}" onclick="event.preventDefault(); document.getElementById('statusForm-{{$category->id}}').submit();"
                                               type="checkbox" {{ $category->status ? 'checked' : '' }} />
                                    </label>

                                    {!! Form::open(array('route' =>['admin.blogs.categories.update',$category->id], 'method'=>'patch' ,'id' => 'statusForm-'.$category->id)) !!}
                                    <input type="hidden" name="status_switch" value="{{ $category->status }}">
                                    {!! Form::close() !!}

                                </td>

                                <td class="text-center">
                                    {{ date('M d, Y',strtotime($category->created_at)) }}
                                </td>

                                <td class="text-end">
                                    <a href="#"
                                       class="btn btn-light btn-active-light-primary btn-flex btn-center btn-sm"
                                       data-kt-menu-trigger="click"
                                       data-kt-menu-placement="bottom-end">{{ __('blog::categories.action') }}
                                        <i class="ki-duotone ki-down fs-5 ms-1"></i></a>

                                    <div
                                            class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-semibold fs-7 w-125px py-4"
                                            data-kt-menu="true">

                                        <div class="menu-item px-3">
                                            <a href="{{ route('admin.blogs.categories.edit',$category->id) }}"
                                               class="menu-link px-3">{{ __('blog::categories.edit') }}</a>
                                        </div>

                                        <div class="menu-item px-3">
                                            <a href="#" class="menu-link px-3 delete_table_row"
                                               data-row="{{ $category->id }}">{{  __('blog::categories.delete')  }}</a>
                                        </div>

                                        <form id="delete_form_{{ $category->id }}" method="post"
                                              action="{{ route('admin.blogs.categories.destroy',$category->id) }}">
                                            @csrf
                                            @method('delete')
                                        </form>

                                    </div>

                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                        <!--end::Table body-->
                    </table>
                    <!--end::Table-->
                </div>

            </div>
        @else
            <div class="card-body p-0">
                <!--begin::Wrapper-->
                <div class="card-px text-center">
                    <!--begin::Title-->
                    <h2 class="fs-2x fw-bold mb-10">{{ __('blog::categories.welcome_to_blog_category') }}</h2>
                    <!--end::Title-->

                    <!--begin::Action-->
                    <a href="{{ route('admin.blogs.categories.create') }}"
                       class="btn btn-primary">{{ __('blog::categories.add_category') }}</a>
                    <!--end::Action-->
                </div>
                <!--end::Wrapper-->
                <!--begin::Illustration-->
                <div class="text-center px-4">
                    <img class="mw-100 mh-300px" alt="" src="{{ asset('vendor/blog/media/empty_blog.png') }}">
                </div>
                <!--end::Illustration-->
            </div>
        @endif
        <!--end::Card body-->
    </div>


</x-default-layout>

resources/views/config.blade.php
<x-default-layout>

    @section('title')
        {{ __('blog::blogs.blog_configuration') }}
    @endsection

    @section('breadcrumbs')
        {{ Breadcrumbs::render('blog.config') }}
    @endsection

    <div class="card card-flush">
        <div class="card-header">
            <div class="card-title">
                <h4>{{ __('blog::blogs.configuration') }}</h4>
            </div>
        </div>

        <div class="card-body py-4" id="analytics_config">

            <form action="{{ route('admin.packages.blog.store') }}" method="post">
                @csrf

                <div class="mb-10">
                    <label class="form-check form-switch form-check-custom form-check-solid">
                        <input class="form-check-input" name="status" type="checkbox" {{(  isset($status ) && $status) ? "checked"  : ''  }} />
                        <span class="form-check-label fw-semibold text-muted">{{ __('blog::blogs.status') }}</span>
                    </label>
                </div>

                <div class="d-flex justify-content-end mb-4">
                    <button type="submit" class="btn btn-info"><span class="indicator-label">{{ __('blog::blogs.submit') }}</span></button>
                </div>

            </form>

        </div>
    </div>


</x-default-layout>